### ISSUE TITLE
Laravel Passport token lifetime

### ISSUE THREAD

**Issue by cheng-yao19** [terion-name/phpstorm-laravel-templates#1]
hello,Have you solved it yet?

**Comment by terion-name** [comment]
em... what?

**Comment by cheng-yao19** [comment]
I see that you have solved this problem on the stackoverflow of "Laravel Passport token lifetime",So I would like to ask you.thanks.
click [there](https://stackoverflow.com/questions/42609436/laravel-passport-token-lifetime)

**Comment by terion-name** [comment]
@cheng-yao19 my comment there:
<img width="680" alt="2018-11-14 21 35 41" src="https://user-images.githubusercontent.com/1060205/48507688-4b6b7d80-e855-11e8-83a5-fdac8dd8c202.png">

Unfortunately

**Comment by terion-name** [comment]
BTW I don't really like passport. It is overcomplicated and badly configurable. I prefer using jwt-auth

**Comment by cheng-yao19** [comment]
OK, I know, I've just looked through the document on passport.The above is written.
"Personal access tokens are always long-lived. Their lifetime is not modified when using the tokensExpireIn or refreshTokensExpireIn methods."
sorry to disturb you.thanks

**Comment by terion-name** [comment]
@cheng-yao19 not a problem :)
